ros_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  # Position Controllers --------------------------------------
  JawL_position_controller:
    type: position_controllers/JointPositionController
    joint: JawL
  JawR_position_controller:
    type: position_controllers/JointPositionController
    joint: JawR
  L6_position_controller:
    type: position_controllers/JointPositionController
    joint: L6
  L5_position_controller:
    type: position_controllers/JointPositionController
    joint: L5
  L4_position_controller:
    type: position_controllers/JointPositionController
    joint: L4
  L3_position_controller:
    type: position_controllers/JointPositionController
    joint: L3
  L2_position_controller:
    type: position_controllers/JointPositionController
    joint: L2
  L1_position_controller:
    type: position_controllers/JointPositionController
    joint: L1